### PR TITLE
dumb (Dynamic Universal Music Bibliotheque): new aport

### PR DESCRIPTION
**Pull request by antonialoytorrens**
The Dynamic Universal Music Bibliotheque port to Alpine Linux.
Depends on allegro4 package.

Patches from debian.

### CODE REVIEW

**Review by DDoSolitary — CHANGES_REQUESTED** [review]
Please squash the commits into a single one, and add an entry to the `build-order` file.

**Comment by antonialoytorrens** [comment]
> Please squash the commits into a single one.

Done!

> Add an entry to the `build-order` file.

Should I put in a new line something like this? ↓
_allegro4 dumb_

**Comment by DDoSolitary** [comment]
@antonialoytorrens 

> Should I put in a new line something like this? ↓
>  _allegro4 dumb_

Yes.

**Comment by antonialoytorrens** [comment]
> @antonialoytorrens
> 
> > Should I put in a new line something like this? ↓
> > _allegro4 dumb_
> 
> Yes.

Done, thank you!

**Pull request merged**
